### ISSUE TITLE
Terminal group bug in `mass.fast_mass2()`

### ISSUE THREAD

**Issue by jlw387** [levitsky/pyteomics#156] opened 2024-09-25 20:04 UTC
DISCLAIMER: I have been using this library for all of about 20 minutes, so this could be user error.

Issue: The function [`mass.fast_mass2()`](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L969) seems to be intentionally adding the two terminal groups onto an input peptide sequence and then failing to parse the terminal groups correctly.

Details: 

From inspection, it looks like the [first chunk of the function](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1002-L1009) is trying to parse a peptide sequence into a standard format. Specifically, it is adding the two ends of the backbone onto an existing peptide sequence, among other things. 
- E.g. for a sequence input of 'G', the output after running this section is a BasicComposition object with the contents {('H-', 1), ('G', 1), ('-OH', 1)}.

The second chunk of the code then tries to map the amino acids in this object to the appropriate masses. I am not sure of all the specifics of this chunk, but the error being thrown for me is [this line](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1020) when processing the group 'H-'. Here is a step through of what the code does:
1. [1014](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1014) 'H-' is checked to see if it is in the provided dictionary of amino acids. It is not, so the code proceeds to the `elif` clause.
2. [1016](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1016) 'H-' is checked to see if it is a terminal group. It is, and so the code proceeds inside the `elif` branch.
3. [1017](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1017) The assertion that 1 == 1 passes.
4. [1018](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1018) The group name is stripped of the '-', leaving just 'H'.
5. [1019](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1019) The modified group name is checked to see if it is an amino acid. 'H' is an amino acid (assuming the default `mass.std_aa_mass` is used), so the code proceeds inside the `if` branch.
6. [1020](https://github.com/levitsky/pyteomics/blob/67b17ef49ebe4f17e6834a6337cf454e26dde5f4/pyteomics/mass/mass.py#L1020) An error is raised, as a terminal group is not supposed to match an amnio acid.

Recommended Fix: It seems like you already check to ensure the group is a valid terminal group at L1016, so unless amino acids are part of those allowable groups, there may be no need to add that extra check. I would recommend removing it and adjusting the `is_term_mod()` function if you want to filter out amino acids with '-' appended.

**Comment by levitsky** [comment] 2024-09-26 10:30
Hi @jlw387, thanks for reporting!
This is definitely a developer error and not a user error :)

Some brief analysis/explanation of my logic:
The addition of terminal groups is intended. However, there are two ways how terminal groups can be parsed. One is if they are just present in `aa_mass`, then that mass is just added. The other is if the terminal group is specified with a "formula". This is a generalization that I made recently, so that both standard "H-", "-OH" and non-standard groups like "-NH2" can be parsed without limitations.

The checks are in this order: first, if a group is in `aa_mass`, it's just used. Standard terminal groups are not present in the standard `aa_mass`.
Then, there is a check that the missing group is a terminal one. And then, before parsing it as a formula, we check if the label is not also present without the hyphen. This is the source of the problem. My idea here was to check if a lowercase modification label is used as a terminal group, because that can lead to incorrect mass calculation. However, it also triggers for `H` because it is both an atom and an amino acid.

I guess the right way to fix this logic is to only trigger the error if the stripped label is lowercase. I will make this change.

**Comment by levitsky** [comment] 2024-09-27 14:14
@jlw387 please feel free to test the current `master` version for you use cases, otherwise I consider it resolved and will close when making the next release.

**Comment by jlw387** [comment] 2024-09-27 16:17
Seems to be working for me; thanks for the quick fix!

**Comment by jlw387** [comment] 2024-09-27 16:18
Oh wait, I did read your comment properly, sorry. I'll re-open for now so you can close with the next release.

**Comment by MSChemicalGeek** [comment] 2024-09-30 22:53
Hello, 

I was going to report similar issue as suddenly as I updated pyteomics (4.5 to 4.7), a lot of mass calculations starting failing with input being a simple polypeptide string. It was complaining about terminal residue invalid and needing to add the new mod to aa_mass. Thanks @jlw387 Looking forward for next release!

**Comment by levitsky** [comment] 2024-10-01 12:49
Thank you everyone for your feedback and sorry for the inconvenience caused by this issue. I have released version 4.7.4 with the fix. Closing this as completed, and please feel free to report any issues with the new version!

**Closed by levitsky** 2024-10-01 12:49 UTC
